### ISSUE TITLE
Attack Rate on ImageNet.

### ISSUE THREAD

**Issue by YogaLYJ** [cassidylaidlaw/ReColorAdv#1]
Thanks for your conding. But I have a question. What is the attack rate for ReColorAdv on ImageNet? I didn't find it in your paper. I just saw four visual results on Page 3.

**Comment by cassidylaidlaw** [comment]
Hi @YogaLYJ, thanks for your interest in our work! I've put a script called `evaluate_imagenet.py` in the repository that downloads a pretrained ImageNet ResNet-50 and runs the ReColorAdv attack against it. I ran it myself on 1,000 images and the model had an accuracy of 3.5% on attacked images.

**Comment by YogaLYJ** [comment]
Thanks！
